### ISSUE TITLE
Query on moving content between chapters

### ISSUE THREAD

**Issue by Ambg05** [DinisCruz/Book_SecDevOps_Risk_Workflow#314]
Is it okay to move the content from Book_SecDevOps_Risk_Workflow/blob/master/content/2.Risk-workflow/For-management/Inaction-is-a-risk.md
to
Book_SecDevOps_Risk_Workflow/blob/master/content/1.Sec-DevOps/DevOps/Performing-root-cause-analysis.md

I hesitate because the first is 'for management' and you might want it to stay there?

**Comment by DinisCruz** [comment]
yes that is fine, a lot of those initial content placement where just placeholders (for later review)

**Comment by Ambg05** [comment]
Great, thanks.
