### ISSUE TITLE
expand on 'Fuzzing WebServices'

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/Book_SecDevOps_Risk_Workflow#47]
See 
- [On Fuzzing WebServices](http://blog.diniscruz.com/2012/05/on-fuzzing-webservices.html)
- [Roadmap for Testing an WebService's Authorization Model](http://blog.diniscruz.com/2012/05/roadmap-for-testing-webservices.html)
- [What is the formula for the WebServices Authentication mappings?](http://blog.diniscruz.com/2012/05/what-is-formula-for-webservices.html)
- [First you create Tests for WebServices, then you add the abuse/security cases](http://blog.diniscruz.com/2012/04/first-you-create-tests-for-webservices.html)
- [If you not blowing up the database, you're not testing the whole app](http://blog.diniscruz.com/2012/04/if-you-not-blowing-up-database-youre.html)
- [A journey into testing WebServices in a developer friendly way](http://blog.diniscruz.com/2012/04/journey-into-testing-webservices-in.html)

**Comment by davevs** [comment]
I call scope creep again. The book has already evolved from 'jira riskflow' to a 'practical guide into handling appsec in agile environments'. I think you should keep it at that level en not go into how you can/should test different technologies. There is plenty of material already available on those topics. The strength of this book should be to provide the necessary glue between appsec and development.

**Comment by DinisCruz** [comment]
Yeah, I think you are right :)

Just added a label called 'scope-creep' so that I can close this issue now and find it later
