### ISSUE TITLE
Question on "In DevOps everything is Code"

### ISSUE THREAD

**Issue by Ambg05** [DinisCruz/Book_SecDevOps_Risk_Workflow#73]
Pull Request #72

A few questions on meaning:

On line 9: 
- I couldn't find a relevant meaning for 'jerkins'
- "you create pristine built"--I'm not sure what this means
- "It should be modifying stuff"--What does 'it' refer to?

On line 19, I just want to be sure I have made sense of the text. If you want me to make further changes let me know.

**Comment by davevs** [comment]
Jerkins should be Jenkins (a popular continuous integration tool).

pristine = without flaws. In other terms; 'first time right'

It refers to the build tool. The whole purpose of CI/CD is that your tools are able to modify stuff.

**Comment by Ambg05** [comment]
Thanks. I've made the changes to Line 9, I'll leave the issue open til I know line 19 is good.

**Comment by DinisCruz** [comment]
_"It should be modifying stuff"_ is actually a mistake, in that context it should say _"it should NOT be modifying stuff."_ 

@Ambg05 don't worry about making that fix I will merge the PR and make a couple more changes

**Comment by DinisCruz** [comment]
ok just an updated version of chapter.

here is the diff of this new version https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow/commit/eab6490feac041523d172069b0fef23ad07db567#diff-6ab070f8156181d34ffb5d5075168bc2

@Ambg05 can you review this file too? (there are significant changes from the last version)

**Comment by DinisCruz** [comment]
closing since this file has been updated and fixed now
